### ISSUE TITLE
[Bug]: extract combo not connected to the blendshape node when one of the sliders is not at 1

### ISSUE THREAD

**Issue by visionmaster2** [blurstudio/Simplex#115] opened 2023-03-13 02:20 UTC
### Summary

Hi, sorry if this is a bug of mine. The problem I'm having is that when I have three sliders, for example, jawOpen = 0.5, smileLeft = 1, and smileRight = 1, I can create a combo and the new blendshape is created and linked in yellow in the blendshape node. However, if I extract the mesh to sculpt it, the blendshape is no longer linked. This problem only occurs when one of the slider values is not at 1

### Expected Behavior

.

### Steps to Reproduce Behavior

.

### Environment

maya 2022

### Additional Context

.

**Comment by tbttfox** [comment] 2023-03-13 05:16
That is a bug, and I can reproduce it easily. I'll see if I can fix it soon.

**Comment by tbttfox** [comment] 2023-03-13 18:31
Looks like I tried to disconnect the same maya connections twice. Since on the second time around, it didn't have anything to disconnect, it clobbered the original disconnection data, meaning the re-connect never happened.
Simple as adding a `list(set())`
Should be fixed in the v3.0.2 release

**Closed by tbttfox** 2023-03-13 18:31 UTC
Labels: bug

**Comment by visionmaster2** [comment] 2023-03-13 22:01
Thank you tbttfox !
